# Generated by Django 5.1 on 2024-08-21 22:05
import sys
from django.db import migrations
from django.conf import settings

TESTING = "test" in sys.argv

migration_operations = (
    [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pg_cron;"),
        migrations.RunSQL(
            "SELECT cron.schedule('* * * * *', $$DELETE FROM secret_secret WHERE burn_at < EXTRACT(EPOCH FROM now()); DELETE FROM secret_verification WHERE burn_at < EXTRACT(EPOCH FROM now()); $$);"
        ),
    ]
    if settings.USE_PG_CRON and not TESTING
    else []
)


class Migration(migrations.Migration):
    dependencies = [
        ("secret", "0001_initial"),
    ]

    operations = migration_operations
