# Generated by Django 5.1 on 2024-08-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secret", "0002_auto_20240821_2205"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verification",
            name="verified",
        ),
        migrations.AlterField(
            model_name="secret",
            name="burn_at",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="secret",
            name="passphrase_hash",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="verification",
            name="burn_at",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
