# Generated by Django 5.1 on 2024-08-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secret", "0003_remove_verification_verified_alter_secret_burn_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="email_hash",
            field=models.TextField(db_index=True, default="random"),
            preserve_default=False,
        ),
    ]
